### ISSUE TITLE
Topic flutter on page load

### ISSUE THREAD

**Issue by didlie** [krixano/ZeroMedium#4]
The list of topics flutters when the page is loading. It appears that the javascript continues to update the list as the page loads. I recommend waiting for the page to load with a GIF or CSS spinner and only load the articles after the page is loaded.

**Comment by krixano** [comment]
Until you know how the zite or ZeroNet zites work, I would refrain from commenting. This flutter could be due to two things, either it's waiting for it to get the topics from the database, or it changes the topics to match the currently logged in user's language. I will not be fixing this because a stupid css spinner isn't going to do anything. Post issues that are actually real and worthwhile to fix next time.
